### ISSUE TITLE
Cooridoors too small

### ISSUE THREAD

**Issue by Vermidia** [Skandarella/Albia-Lost-Places-Metaroom#3]
The underground bit, and the basement under the island are too short. There might be a few others this height, but what it does is cause adult norns or breeds slightly bigger than normal to clip through or be unable to travel (when using teleporters).

**Comment by Skandarella** [comment]
Basement under the castle, room under the island and jungle have been enheighted: https://www.dropbox.com/s/ugqab98eml2qr8n/Albia%20lost%20PlacesC13NewBasement.bmp?dl=0
