### ISSUE TITLE
Dont know how to upload

### ISSUE THREAD

**Issue by Skandarella** [Skandarella/Albia-Lost-Places-Metaroom#5]
Hey,

please someone else upload the files of the metaroom here, i watched guides but it is really too complicated for me to understand to upload files here.

**Comment by JennaMalkin** [comment]
In this repository, go to Settings, Manage Access, and invite me or Verm as a collaborator.  https://github.com/Skandarella/Albia-Lost-Places-Metaroom/settings/access - it will ask you again for your password.

Once either Verm or I accept the invite I think they should have commit access (i.e. upload access)

But you may need to go back in to the same page afterwards and double check
